### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/Users/als/.atom/packages/angularjs'

### ISSUE THREAD

**Issue by heyalbert** [atom/deprecation-cop#25]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.175.0
**System**: Mac OS X 10.9.5
**Thrown From**: [deprecation-cop](https://github.com/atom/deprecation-cop) package, v0.32.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/Users/als/.atom/packages/angularjs'

```
At /Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:52

Error: ENOENT, no such file or directory '/Users/als/.atom/packages/angularjs'
  at Error (native)
  at fs.lstatSync (fs.js:716:18)
  at Object.fs.lstatSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:115:14)
  at Object.realpathSync (fs.js:1295:21)
  at Object.fs.realpathSync (/Applications/Atom.app/Contents/Resources/atom/common/lib/asar.js:198:27)
  at DeprecationCopView.module.exports.DeprecationCopView.getPackageName (/Applications/Atom.app/Contents/Resources/app/node_modules/deprecation-cop/lib/deprecation-cop-view.js:200:42)
  at DeprecationCopView.module.exports.DeprecationCopView.updateCalls (/Applications/Atom.app/Contents/Resources/app/node_modules/deprecation-cop/lib/deprecation-cop-view.js:252:121)
  at HTMLButtonElement.<anonymous> (/Applications/Atom.app/Contents/Resources/app/node_modules/deprecation-cop/lib/deprecation-cop-view.js:119:24)
  at HTMLButtonElement.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLButtonElement.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
  2x -1:19.5 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
     -1:02.0 settings-view:open (div.deprecation-cop.pane-item.native-key-bindings)
 11x -0:30.5 core:backspace (atom-text-editor.editor.mini)
     -0:00.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "feedback",
      "git-difftool"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ],
    "projectHome": "/users/als/Sites"
  }
}
```

### Installed Packages

```coffee
# User
Atom-Syntax-highlighting-for-Sass, v0.5.0
autoclose-html, v0.14.0
autocomplete-paths, v1.0.0
autocomplete-snippets, v1.0.0
color-picker, v1.4.4
language-docker, v1.1.2
open-last-project, v0.1.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by kevinsawicki** [comment]
Fixed by https://github.com/atom/deprecation-cop/commit/c8620794a35783b625183f89428ffb20bbfd6792
