### ISSUE TITLE
Uncaught Error: ENOENT, no such file or directory '/home/jpeeler/.atom/packages/term2'

### ISSUE THREAD

**Issue by jpeeler** [atom/deprecation-cop#27]
[Enter steps to reproduce below:]

1. Removed package that was incompatible with current version of Atom (term2)
2. Clicked refresh on deprecation cop window.

**Atom Version**: 0.176.0
**System**: linux 3.18.3-201.fc21.x86_64
**Thrown From**: [deprecation-cop](https://github.com/atom/deprecation-cop) package, v0.33.0

### Stack Trace

Uncaught Error: ENOENT, no such file or directory '/home/jpeeler/.atom/packages/term2'

```
At /usr/share/atom/resources/atom/common/lib/asar.js:52

Error: ENOENT, no such file or directory '/home/jpeeler/.atom/packages/term2'
  at Error (native)
  at fs.lstatSync (fs.js:716:18)
  at Object.fs.lstatSync (/usr/share/atom/resources/atom/common/lib/asar.js:115:14)
  at Object.realpathSync (fs.js:1295:21)
  at Object.fs.realpathSync (/usr/share/atom/resources/atom/common/lib/asar.js:198:27)
  at DeprecationCopView.module.exports.DeprecationCopView.getPackageName (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-view.js:200:42)
  at DeprecationCopView.module.exports.DeprecationCopView.updateCalls (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-view.js:252:121)
  at HTMLButtonElement.<anonymous> (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-view.js:119:24)
  at HTMLButtonElement.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4430:9)
  at HTMLButtonElement.elemData.handle (/usr/share/atom/resources/app/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -3:28.0 pane:reopen-closed-item (atom-text-editor.editor)
     -3:16.8 asciidoc-preview:toggle (atom-text-editor.editor)
     -2:36.4 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -2:09.0 deprecation-cop:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:44.7 incompatible-packages:view (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -1:10.7 settings-view:install-packages (atom-workspace.workspace.scrollbars-visible-always.theme-atom-dark-syntax.theme-atom-dark-ui)
     -0:59.4 settings-view:open (button.btn)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode"
    ]
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.4.2
autocomplete-plus, v2.0.6
minimap, v3.5.6
minimap-git-diff, v3.1.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by 50Wliu** [comment]
I believe this will be fixed in the next Atom version, 0.177.0.
