### ISSUE TITLE
Error from DeprecationCopStatusBarView on startup with 0.123.0

### ISSUE THREAD

**Issue by sirianni** [atom/deprecation-cop#3]
Upon startup, I get this error in the chrome debug console.  This started appearing after an update to Atom 0.123.0.  I'm running on Ubuntu 14.04.
```
TypeError: undefined is not a function
  at DeprecationCopStatusBarView.module.exports.DeprecationCopStatusBarView.update (/opt/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:59:21)
  at DeprecationCopStatusBarView.update (/opt/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:3:61)
  at DeprecationCopStatusBarView.module.exports.DeprecationCopStatusBarView.afterAttach (/opt/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:49:12)
  at callAttachHook (/opt/atom/resources/app/node_modules/space-pen/lib/space-pen.js:333:107)
  at [object Object].jQuery.fn.(anonymous function) [as append] (/opt/atom/resources/app/node_modules/space-pen/lib/space-pen.js:349:9)
  at StatusBarView.module.exports.StatusBarView.appendRight (/opt/atom/resources/app/node_modules/status-bar/lib/status-bar-view.js:87:30)
  at /opt/atom/resources/app/node_modules/deprecation-cop/lib/main.js:41:88
  at /opt/atom/resources/app/node_modules/emissary/lib/emitter.js:85:24
  at PackageManager.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/emissary/lib/emitter.js:118:15)
  at PackageManager.module.exports.PackageManager.activate (/opt/atom/resources/app/src/package-manager.js:87:19)
  at Atom.module.exports.Atom.startEditorWindow (/opt/atom/resources/app/src/atom.js:373:21)
  at Object.<anonymous> (/opt/atom/resources/app/src/window-bootstrap.js:14:8)
  at Object.<anonymous> (/opt/atom/resources/app/src/window-bootstrap.js:20:4)
  at Module._compile (module.js:455:26)
  at Object.Module._extensions..js (module.js:473:10)
  at Module.load (/opt/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:311:12)
  at Module.require (module.js:363:17)
  at require (module.js:379:17)
  at window.onload (file:///opt/atom/resources/app/static/index.js:20:25)
 index.js:29
window.onload index.js:29
```

**Comment by kevinsawicki** [comment]
I'm going to close this out, I don't think this is happening any longer with the latest version of this package.
