### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by danielmelogpi** [atom/deprecation-cop#42]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.174.0
**System**: linux 3.19.0-16-generic
**Thrown From**: [deprecation-cop](https://github.com/atom/deprecation-cop) package, v0.32.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /usr/share/atom/resources/app/node_modules/deprecation-cop/node_modules/atom-selector-linter/lib/helpers.js:11

TypeError: undefined is not a function
  at module.exports.eachSelector (/usr/share/atom/resources/app/node_modules/deprecation-cop/node_modules/atom-selector-linter/lib/helpers.js:11:18)
  at SelectorLinter.module.exports.SelectorLinter.checkUIStylesheet (/usr/share/atom/resources/app/node_modules/deprecation-cop/node_modules/atom-selector-linter/lib/selector-linter.js:75:7)
  at SelectorLinter.module.exports.SelectorLinter.checkPackage (/usr/share/atom/resources/app/node_modules/deprecation-cop/node_modules/atom-selector-linter/lib/selector-linter.js:56:30)
  at Object.exports.getSelectorDeprecations (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/helpers.js:14:14)
  at exports.getSelectorDeprecationsCount (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/helpers.js:22:41)
  at DeprecationCopStatusBarView.module.exports.DeprecationCopStatusBarView.getDeprecatedSelectorCount (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:70:115)
  at DeprecationCopStatusBarView.module.exports.DeprecationCopStatusBarView.update (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:80:52)
  at DeprecationCopStatusBarView.update (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:3:61)
  at DeprecationCopStatusBarView.module.exports.DeprecationCopStatusBarView.attached (/usr/share/atom/resources/app/node_modules/deprecation-cop/lib/deprecation-cop-status-bar-view.js:61:12)
  at space-pen-div.View.element.attached (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:164:63)
  at space-pen-div.CustomElementPrototype.attachedCallback (/home/daniel/.atom/packages/csslint/node_modules/atom-message-panel/node_modules/space-pen/lib/space-pen.js:51:55)
  at status-bar.StatusBarView.addRightTile (/usr/share/atom/resources/app/node_modules/status-bar/lib/status-bar-view.js:97:23)
  at /usr/share/atom/resources/app/node_modules/deprecation-cop/lib/main.js:46:23
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at /usr/share/atom/resources/app/src/package-manager.js:416:32
  at _fulfilled (/usr/share/atom/resources/app/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/usr/share/atom/resources/app/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/usr/share/atom/resources/app/node_modules/q/q.js:749:13)
  at /usr/share/atom/resources/app/node_modules/q/q.js:557:44
  at flush (/usr/share/atom/resources/app/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:386:11)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
colorful-json, v0.1.0
csslint, v1.0.2
emmet, v2.3.2
git-diff-details, v0.5.0
git-log, v0.2.0
jslint, v1.0.1
pretty-json, v0.3.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by mnquintana** [comment]
You're running an extremely old version of Atom - please update to the latest version (0.198.0).
